# Linear Algebra with NumPy and Scipy

In [6]:
import numpy as np
import scipy.linalg as la

# Operation
## 1. Transpose

In [9]:
# Numpy
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print(A.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [12]:
# Create a tensor
B = np.random.random((5,4,3))
print(B.shape)
B_t = np.transpose(B, (2,1,0))
print(B_t.shape)

(5, 4, 3)
(3, 4, 5)


## 2.1 Element-wise product
Just use the arthmetic operator for multiplication for two matrices

In [13]:
A = np.array([[1,2],[3,4]])
B = np.array([[2,2],[3,3]])
C = A * B
print(C)

[[ 2  4]
 [ 9 12]]


## 3. Matrix Product
Use the @ operator

In [15]:
C = A @ B
print(C)

[[ 8  8]
 [18 18]]


## 4. Inverse Matrix
Definition: $A(A^{-1}) = I$

In [20]:
# Numpy
A = np.array([[1,2,3],[4,5,6], [7,8,9]])
A_det = np.linalg.det(A)
# A_inv = np.linalg.inv(A)
print(A_det)
# print(A_inv)

0.0


## 5. Permutation Matrix
Just think of it as rearrange your identity matrix  

In [25]:
A = np.random.random((3,3))
A_perm = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(A)
print(A@A_perm)

[[0.23406792 0.41735661 0.2188929 ]
 [0.85907918 0.89893621 0.95752813]
 [0.93923747 0.49159196 0.30921962]]
[[0.23406792 0.41735661 0.2188929 ]
 [0.85907918 0.89893621 0.95752813]
 [0.93923747 0.49159196 0.30921962]]


## 6. Solving system of linear equations
Example:
$$X_1 + 5x_2 = 7$$
$$-2x_1 - 7x_2 = -5$$

In [30]:
# Rrote the linear aquations as two seprate arrays
var_A = np.array([[1,5],[-2,-7]])
A = np.array([[7,-5]])

# Sove the linear equations using the scipy module
ans_A = la.solve(var_A, A.T)
print(ans_A)

[[-8.]
 [ 3.]]


## 7. Gaussian Elimination  
Step 1: From the augmented matrix

In [31]:
aug_A = np.hstack((var_A, A.T))
print(aug_A)

[[ 1  5  7]
 [-2 -7 -5]]


### Stp 2: Gaussian elimination
Involves 2 elementary row operations
1. Add k times row j to i
1. Multiply row i by scalar k

In [36]:
def add_row(A, k, j, i):
    n = A.shape[0]
    E = np.eye(n)
    if i == j:
        E[i,i] = k + 1
    else:
        E[i,j] = k
    return E@A

def scale_row(A, i, k):
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = k
    return E@A

### Step 3: Use the two row operations to form a triangular matrix 

In [37]:
B = add_row(aug_A, 2, 0, 1)
print(B)

[[1. 5. 7.]
 [0. 3. 9.]]


In [38]:
B = scale_row(B, 1, 1/3)
print(B)

[[1. 5. 7.]
 [0. 1. 3.]]


Step 4: Continue using the 2 operations until you get identity matrix for the variables. T

In [40]:
B = add_row(B, -5, 1, 0)
print(B)

[[ 1.  0. -8.]
 [ 0.  1.  3.]]



## Permutation matrix on Gaussian Eliminatoin
Sometimes permutaiont matrix can be useful to swap sround rows to form your triangular matrix
Example:
$$2x_2 = 4 $$
$$3x_1 - 2x2 = 5 $$

In [43]:
var_A = np.array([[0,2],[3,-2]])
A = np.array(([[4,5]]))                 
aug_A = np.hstack((var_A, A.T))
print(aug_A)

[[ 0  2  4]
 [ 3 -2  5]]


In [44]:
# Helper function to switch row
def swith_rows(A, i, j):
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = 0
    E[j,j] = 0
    E[i,j] = 1
    E[j,i] = 1
    return E@A

In [46]:
B = swith_rows(aug_A, 0, 1)
print(B)

[[ 3. -2.  5.]
 [ 0.  2.  4.]]


In [47]:
B = scale_row(B, 0, 1/3)
print(B)

[[ 1.         -0.66666667  1.66666667]
 [ 0.          2.          4.        ]]


In [48]:
A = np.array([4,5])
B = np.array([12,13])
li_norm = la.norm(B-A, ord=1)
print(li_norm)

16.0


In [49]:
l2_norm = la.norm(B-A)
print(l2_norm)

11.313708498984761
